Make test scripts' "skip" notices more consistent.
* Always issue a notice when skipping the test.
* Always prefix the message with the script's identity (`$0`).
* Drop the word "test" from the end of the notice since the script now
  identifies itself by name.
* Always explicitly state that "skipping" is the outcome of the script.

diff --git a/contrib/mom/examples/test-mom.sh.in b/contrib/mom/examples/test-mom.sh.in
--- a/contrib/mom/examples/test-mom.sh.in
+++ b/contrib/mom/examples/test-mom.sh.in
@@ -42,7 +42,7 @@ for cmd in pdfinfo pdfimages
 do
     if ! command -v $cmd >/dev/null
     then
-        echo "cannot locate '$cmd' command; skipping test" >&2
+        echo "$0: cannot locate '$cmd' command; skipping" >&2
         exit 77 # skip
     fi
 done
@@ -85,6 +85,8 @@ check_has_images()
     fi
 }
 
+# TODO: Make this a "hard error" (status 99).  See, e.g.,
+# "font/devpdf/tests/check-default-foundry.sh.in".
 for k in $examples
 do
     if ! [ -f "$examplesdir"/$k ]
